### ISSUE TITLE
How to can I have time with millisecond precision

### ISSUE THREAD

**Issue by jerome-laforge** [inconshreveable/log15#72] opened 2015-12-15 15:13 UTC
Hello, 
I didn't find any examples into godoc of log15 for set time with millisecond precision.

Is it possible? if yes, how I can enabled it?

Many thx

**Comment by ChrisHines** [comment] 2015-12-15 16:00
Closing as a duplicate of #35. Please continue discussion on that issue. Thanks.

**Closed by ChrisHines** 2015-12-15 16:00 UTC
